#!/usr/bin/env python
import gtk, sys, gnome
from optparse import OptionParser

parser = OptionParser()
parser.add_option ("-s", "--simulate", action="store_true", dest="simulate",
                   help="Recording operations will be done in simulation mode.",
                   default=False)

(options, args) = parser.parse_args()

# Clean up argv before we load gst
sys.argv = sys.argv[:1]

# Data dir:
import os.path

bins_dir = os.path.dirname (os.path.abspath (sys.argv[0]))
prefix_dir = os.path.dirname (bins_dir)
data_dir = os.path.join (prefix_dir, 'share', 'serpentine')
lib_dir = os.path.join (prefix_dir, 'lib',
                        "python%d.%d" % sys.version_info[0:2],
                        'site-packages')
# Add our default lib dir to the path
if os.path.isdir (lib_dir) and lib_dir not in sys.path:
	sys.path.append (lib_dir)

from serpentine import Serpentine

s = Serpentine (data_dir)
app = gnome.init ('serpentine', s.preferences.version)
s.simulate = options.simulate
s.show()
gtk.main()
del s
del app
