#include "tcountries.h"
#include <glib/gi18n.h>
#include <glib.h>

static void t_countries_init (void);

G_LOCK_DEFINE_STATIC (t_countries);

static GHashTable *t_countries = NULL;

const gchar *
t_code_to_country (const gchar *code)
{
	/* make sure this is run */
	t_countries_init ();
	return (const gchar *) g_hash_table_lookup (t_countries, code);
}

static void
t_countries_finalize (void)
{
	G_LOCK (t_countries);
	g_hash_table_destroy (t_countries);
	t_countries = NULL;
	G_UNLOCK (t_countries);
}

static void
t_countries_init (void)
{
	G_LOCK (t_countries);
	if (t_countries) {
		G_UNLOCK (t_countries);
		return;
	}
	t_countries = g_hash_table_new (g_str_hash, g_str_equal);
	g_atexit (t_countries_finalize);
	/* load db */
	g_hash_table_insert (t_countries, "af", _("Afghanistan"));
	g_hash_table_insert (t_countries, "al", _("Albania"));
	g_hash_table_insert (t_countries, "dz", _("Algeria"));
	g_hash_table_insert (t_countries, "as", _("American Samoa"));
	g_hash_table_insert (t_countries, "ad", _("Andorra"));
	g_hash_table_insert (t_countries, "ao", _("Angola"));
	g_hash_table_insert (t_countries, "ai", _("Anguilla"));
	g_hash_table_insert (t_countries, "aq", _("Antarctica"));
	g_hash_table_insert (t_countries, "ag", _("Antigua and Barbuda"));
	g_hash_table_insert (t_countries, "ar", _("Argentina"));
	g_hash_table_insert (t_countries, "am", _("Armenia"));
	g_hash_table_insert (t_countries, "aw", _("Aruba"));
	g_hash_table_insert (t_countries, "au", _("Australia"));
	g_hash_table_insert (t_countries, "at", _("Austria"));
	g_hash_table_insert (t_countries, "az", _("Azerbaijan"));
	g_hash_table_insert (t_countries, "bs", _("Bahamas"));
	g_hash_table_insert (t_countries, "bh", _("Bahrain"));
	g_hash_table_insert (t_countries, "bd", _("Bangladesh"));
	g_hash_table_insert (t_countries, "bb", _("Barbados"));
	g_hash_table_insert (t_countries, "by", _("Belarus"));
	g_hash_table_insert (t_countries, "be", _("Belgium"));
	g_hash_table_insert (t_countries, "bz", _("Belize"));
	g_hash_table_insert (t_countries, "bj", _("Benin"));
	g_hash_table_insert (t_countries, "bm", _("Bermuda"));
	g_hash_table_insert (t_countries, "bt", _("Bhutan"));
	g_hash_table_insert (t_countries, "bo", _("Bolivia"));
	g_hash_table_insert (t_countries, "ba", _("Bosnia and Herzegowina"));
	g_hash_table_insert (t_countries, "bw", _("Botswana"));
	g_hash_table_insert (t_countries, "bv", _("Bouvet Island"));
	g_hash_table_insert (t_countries, "br", _("Brazil"));
	g_hash_table_insert (t_countries, "io", _("British Indian Ocean Territory"));
	g_hash_table_insert (t_countries, "bn", _("Brunei Darussalam"));
	g_hash_table_insert (t_countries, "bg", _("Bulgaria"));
	g_hash_table_insert (t_countries, "bf", _("Burkina Faso"));
	g_hash_table_insert (t_countries, "bi", _("Burundi"));
	g_hash_table_insert (t_countries, "kh", _("Cambodia"));
	g_hash_table_insert (t_countries, "cm", _("Cameroon"));
	g_hash_table_insert (t_countries, "ca", _("Canada"));
	g_hash_table_insert (t_countries, "cv", _("Cape Verde"));
	g_hash_table_insert (t_countries, "ky", _("Cayman Islands"));
	g_hash_table_insert (t_countries, "cf", _("Central African Republic"));
	g_hash_table_insert (t_countries, "td", _("Chad"));
	g_hash_table_insert (t_countries, "cl", _("Chile"));
	g_hash_table_insert (t_countries, "cn", _("China"));
	g_hash_table_insert (t_countries, "cx", _("Christmas Island"));
	g_hash_table_insert (t_countries, "cc", _("Cocos (Keeling) Islands"));
	g_hash_table_insert (t_countries, "co", _("Colombia"));
	g_hash_table_insert (t_countries, "km", _("Comoros"));
	g_hash_table_insert (t_countries, "cd", _("Congo, Democratic Republic of (Was Zaire)"));
	g_hash_table_insert (t_countries, "cg", _("Congo, People'S Republic of"));
	g_hash_table_insert (t_countries, "ck", _("Cook Islands"));
	g_hash_table_insert (t_countries, "cr", _("Costa Rica"));
	g_hash_table_insert (t_countries, "ci", _("Cote D'Ivoire"));
	g_hash_table_insert (t_countries, "hr", _("Croatia (Local Name: Hrvatska)"));
	g_hash_table_insert (t_countries, "cu", _("Cuba"));
	g_hash_table_insert (t_countries, "cy", _("Cyprus"));
	g_hash_table_insert (t_countries, "cz", _("Czech Republic"));
	g_hash_table_insert (t_countries, "dk", _("Denmark"));
	g_hash_table_insert (t_countries, "dj", _("Djibouti"));
	g_hash_table_insert (t_countries, "dm", _("Dominica"));
	g_hash_table_insert (t_countries, "do", _("Dominican Republic"));
	g_hash_table_insert (t_countries, "tl", _("East Timor"));
	g_hash_table_insert (t_countries, "ec", _("Ecuador"));
	g_hash_table_insert (t_countries, "eg", _("Egypt"));
	g_hash_table_insert (t_countries, "sv", _("El Salvador"));
	g_hash_table_insert (t_countries, "gq", _("Equatorial Guinea"));
	g_hash_table_insert (t_countries, "er", _("Eritrea"));
	g_hash_table_insert (t_countries, "ee", _("Estonia"));
	g_hash_table_insert (t_countries, "et", _("Ethiopia"));
	g_hash_table_insert (t_countries, "fk", _("Falkland Islands (Malvinas)"));
	g_hash_table_insert (t_countries, "fo", _("Faroe Islands"));
	g_hash_table_insert (t_countries, "fj", _("Fiji"));
	g_hash_table_insert (t_countries, "fi", _("Finland"));
	g_hash_table_insert (t_countries, "fr", _("France"));
	g_hash_table_insert (t_countries, "fx", _("France, Metropolitan"));
	g_hash_table_insert (t_countries, "gf", _("French Guiana"));
	g_hash_table_insert (t_countries, "pf", _("French Polynesia"));
	g_hash_table_insert (t_countries, "tf", _("French Southern Territories"));
	g_hash_table_insert (t_countries, "ga", _("Gabon"));
	g_hash_table_insert (t_countries, "gm", _("Gambia"));
	g_hash_table_insert (t_countries, "ge", _("Georgia"));
	g_hash_table_insert (t_countries, "de", _("Germany"));
	g_hash_table_insert (t_countries, "gh", _("Ghana"));
	g_hash_table_insert (t_countries, "gi", _("Gibraltar"));
	g_hash_table_insert (t_countries, "gr", _("Greece"));
	g_hash_table_insert (t_countries, "gl", _("Greenland"));
	g_hash_table_insert (t_countries, "gd", _("Grenada"));
	g_hash_table_insert (t_countries, "gp", _("Guadeloupe"));
	g_hash_table_insert (t_countries, "gu", _("Guam"));
	g_hash_table_insert (t_countries, "gt", _("Guatemala"));
	g_hash_table_insert (t_countries, "gn", _("Guinea"));
	g_hash_table_insert (t_countries, "gw", _("Guinea-Bissau"));
	g_hash_table_insert (t_countries, "gy", _("Guyana"));
	g_hash_table_insert (t_countries, "ht", _("Haiti"));
	g_hash_table_insert (t_countries, "hm", _("Heard and Mc Donald Islands"));
	g_hash_table_insert (t_countries, "hn", _("Honduras"));
	g_hash_table_insert (t_countries, "hk", _("Hong Kong"));
	g_hash_table_insert (t_countries, "hu", _("Hungary"));
	g_hash_table_insert (t_countries, "is", _("Iceland"));
	g_hash_table_insert (t_countries, "in", _("India"));
	g_hash_table_insert (t_countries, "id", _("Indonesia"));
	g_hash_table_insert (t_countries, "ir", _("Iran (Islamic Republic of)"));
	g_hash_table_insert (t_countries, "iq", _("Iraq"));
	g_hash_table_insert (t_countries, "ie", _("Ireland"));
	g_hash_table_insert (t_countries, "il", _("Israel"));
	g_hash_table_insert (t_countries, "it", _("Italy"));
	g_hash_table_insert (t_countries, "jm", _("Jamaica"));
	g_hash_table_insert (t_countries, "jp", _("Japan"));
	g_hash_table_insert (t_countries, "jo", _("Jordan"));
	g_hash_table_insert (t_countries, "kz", _("Kazakhstan"));
	g_hash_table_insert (t_countries, "ke", _("Kenya"));
	g_hash_table_insert (t_countries, "ki", _("Kiribati"));
	g_hash_table_insert (t_countries, "kp", _("Korea, Democratic People'S Republic of"));
	g_hash_table_insert (t_countries, "kr", _("Korea, Republic of"));
	g_hash_table_insert (t_countries, "kw", _("Kuwait"));
	g_hash_table_insert (t_countries, "kg", _("Kyrgyzstan"));
	g_hash_table_insert (t_countries, "la", _("Lao People'S Democratic Republic"));
	g_hash_table_insert (t_countries, "lv", _("Latvia"));
	g_hash_table_insert (t_countries, "lb", _("Lebanon"));
	g_hash_table_insert (t_countries, "ls", _("Lesotho"));
	g_hash_table_insert (t_countries, "lr", _("Liberia"));
	g_hash_table_insert (t_countries, "ly", _("Libyan Arab Jamahiriya"));
	g_hash_table_insert (t_countries, "li", _("Liechtenstein"));
	g_hash_table_insert (t_countries, "lt", _("Lithuania"));
	g_hash_table_insert (t_countries, "lu", _("Luxembourg"));
	g_hash_table_insert (t_countries, "mo", _("Macau"));
	g_hash_table_insert (t_countries, "mk", _("Macedonia, The Former Yugoslav Republic of"));
	g_hash_table_insert (t_countries, "mg", _("Madagascar"));
	g_hash_table_insert (t_countries, "mw", _("Malawi"));
	g_hash_table_insert (t_countries, "my", _("Malaysia"));
	g_hash_table_insert (t_countries, "mv", _("Maldives"));
	g_hash_table_insert (t_countries, "ml", _("Mali"));
	g_hash_table_insert (t_countries, "mt", _("Malta"));
	g_hash_table_insert (t_countries, "mh", _("Marshall Islands"));
	g_hash_table_insert (t_countries, "mq", _("Martinique"));
	g_hash_table_insert (t_countries, "mr", _("Mauritania"));
	g_hash_table_insert (t_countries, "mu", _("Mauritius"));
	g_hash_table_insert (t_countries, "yt", _("Mayotte"));
	g_hash_table_insert (t_countries, "mx", _("Mexico"));
	g_hash_table_insert (t_countries, "fm", _("Micronesia, Federated States of"));
	g_hash_table_insert (t_countries, "md", _("Moldova, Republic of"));
	g_hash_table_insert (t_countries, "mc", _("Monaco"));
	g_hash_table_insert (t_countries, "mn", _("Mongolia"));
	g_hash_table_insert (t_countries, "ms", _("Montserrat"));
	g_hash_table_insert (t_countries, "ma", _("Morocco"));
	g_hash_table_insert (t_countries, "mz", _("Mozambique"));
	g_hash_table_insert (t_countries, "mm", _("Myanmar"));
	g_hash_table_insert (t_countries, "na", _("Namibia"));
	g_hash_table_insert (t_countries, "nr", _("Nauru"));
	g_hash_table_insert (t_countries, "np", _("Nepal"));
	g_hash_table_insert (t_countries, "nl", _("Netherlands"));
	g_hash_table_insert (t_countries, "an", _("Netherlands Antilles"));
	g_hash_table_insert (t_countries, "nc", _("New Caledonia"));
	g_hash_table_insert (t_countries, "nz", _("New Zealand"));
	g_hash_table_insert (t_countries, "ni", _("Nicaragua"));
	g_hash_table_insert (t_countries, "ne", _("Niger"));
	g_hash_table_insert (t_countries, "ng", _("Nigeria"));
	g_hash_table_insert (t_countries, "nu", _("Niue"));
	g_hash_table_insert (t_countries, "nf", _("Norfolk Island"));
	g_hash_table_insert (t_countries, "mp", _("Northern Mariana Islands"));
	g_hash_table_insert (t_countries, "no", _("Norway"));
	g_hash_table_insert (t_countries, "om", _("Oman"));
	g_hash_table_insert (t_countries, "pk", _("Pakistan"));
	g_hash_table_insert (t_countries, "pw", _("Palau"));
	g_hash_table_insert (t_countries, "ps", _("Palestinian Territory, Occupied"));
	g_hash_table_insert (t_countries, "pa", _("Panama"));
	g_hash_table_insert (t_countries, "pg", _("Papua New Guinea"));
	g_hash_table_insert (t_countries, "py", _("Paraguay"));
	g_hash_table_insert (t_countries, "pe", _("Peru"));
	g_hash_table_insert (t_countries, "ph", _("Philippines"));
	g_hash_table_insert (t_countries, "pn", _("Pitcairn"));
	g_hash_table_insert (t_countries, "pl", _("Poland"));
	g_hash_table_insert (t_countries, "pt", _("Portugal"));
	g_hash_table_insert (t_countries, "pr", _("Puerto Rico"));
	g_hash_table_insert (t_countries, "qa", _("Qatar"));
	g_hash_table_insert (t_countries, "re", _("Reunion"));
	g_hash_table_insert (t_countries, "ro", _("Romania"));
	g_hash_table_insert (t_countries, "ru", _("Russian Federation"));
	g_hash_table_insert (t_countries, "rw", _("Rwanda"));
	g_hash_table_insert (t_countries, "kn", _("Saint Kitts and Nevis"));
	g_hash_table_insert (t_countries, "lc", _("Saint Lucia"));
	g_hash_table_insert (t_countries, "vc", _("Saint Vincent and The Grenadines"));
	g_hash_table_insert (t_countries, "ws", _("Samoa"));
	g_hash_table_insert (t_countries, "sm", _("San Marino"));
	g_hash_table_insert (t_countries, "st", _("Sao Tome and Principe"));
	g_hash_table_insert (t_countries, "sa", _("Saudi Arabia"));
	g_hash_table_insert (t_countries, "sn", _("Senegal"));
	g_hash_table_insert (t_countries, "sc", _("Seychelles"));
	g_hash_table_insert (t_countries, "sl", _("Sierra Leone"));
	g_hash_table_insert (t_countries, "sg", _("Singapore"));
	g_hash_table_insert (t_countries, "sk", _("Slovakia (Slovak Republic)"));
	g_hash_table_insert (t_countries, "si", _("Slovenia"));
	g_hash_table_insert (t_countries, "sb", _("Solomon Islands"));
	g_hash_table_insert (t_countries, "so", _("Somalia"));
	g_hash_table_insert (t_countries, "za", _("South Africa"));
	g_hash_table_insert (t_countries, "gs", _("South Georgia and The South Sandwich Islands"));
	g_hash_table_insert (t_countries, "es", _("Spain"));
	g_hash_table_insert (t_countries, "lk", _("Sri Lanka"));
	g_hash_table_insert (t_countries, "sh", _("St. Helena"));
	g_hash_table_insert (t_countries, "pm", _("St. Pierre and Miquelon"));
	g_hash_table_insert (t_countries, "sd", _("Sudan"));
	g_hash_table_insert (t_countries, "sr", _("Suriname"));
	g_hash_table_insert (t_countries, "sj", _("Svalbard and Jan Mayen Islands"));
	g_hash_table_insert (t_countries, "sz", _("Swaziland"));
	g_hash_table_insert (t_countries, "se", _("Sweden"));
	g_hash_table_insert (t_countries, "ch", _("Switzerland"));
	g_hash_table_insert (t_countries, "sy", _("Syrian Arab Republic"));
	g_hash_table_insert (t_countries, "tw", _("Taiwan"));
	g_hash_table_insert (t_countries, "tj", _("Tajikistan"));
	g_hash_table_insert (t_countries, "tz", _("Tanzania, United Republic of"));
	g_hash_table_insert (t_countries, "th", _("Thailand"));
	g_hash_table_insert (t_countries, "tg", _("Togo"));
	g_hash_table_insert (t_countries, "tk", _("Tokelau"));
	g_hash_table_insert (t_countries, "to", _("Tonga"));
	g_hash_table_insert (t_countries, "tt", _("Trinidad and Tobago"));
	g_hash_table_insert (t_countries, "tn", _("Tunisia"));
	g_hash_table_insert (t_countries, "tr", _("Turkey"));
	g_hash_table_insert (t_countries, "tm", _("Turkmenistan"));
	g_hash_table_insert (t_countries, "tc", _("Turks and Caicos Islands"));
	g_hash_table_insert (t_countries, "tv", _("Tuvalu"));
	g_hash_table_insert (t_countries, "ug", _("Uganda"));
	g_hash_table_insert (t_countries, "ua", _("Ukraine"));
	g_hash_table_insert (t_countries, "ae", _("United Arab Emirates"));
	g_hash_table_insert (t_countries, "gb", _("United Kingdom"));
	g_hash_table_insert (t_countries, "us", _("United States"));
	g_hash_table_insert (t_countries, "um", _("United States Minor Outlying Islands"));
	g_hash_table_insert (t_countries, "uy", _("Uruguay"));
	g_hash_table_insert (t_countries, "uz", _("Uzbekistan"));
	g_hash_table_insert (t_countries, "vu", _("Vanuatu"));
	g_hash_table_insert (t_countries, "va", _("Vatican City State (Holy See)"));
	g_hash_table_insert (t_countries, "ve", _("Venezuela"));
	g_hash_table_insert (t_countries, "vn", _("Viet Nam"));
	g_hash_table_insert (t_countries, "vg", _("Virgin Islands (British)"));
	g_hash_table_insert (t_countries, "vi", _("Virgin Islands (U.S.)"));
	g_hash_table_insert (t_countries, "wf", _("Wallis and Futuna Islands"));
	g_hash_table_insert (t_countries, "eh", _("Western Sahara"));
	g_hash_table_insert (t_countries, "ye", _("Yemen"));
	g_hash_table_insert (t_countries, "yu", _("Yugoslavia"));
	g_hash_table_insert (t_countries, "zm", _("Zambia"));
	g_hash_table_insert (t_countries, "zw", _("Zimbabwe"));
	G_UNLOCK (t_countries);
}
